version: '3.8'

services:
  mcp-serper:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-serper:latest
    container_name: mcp-serper
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  demo-client:
    image: nginx:alpine
    container_name: mcp-serper-demo
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./demo:/usr/share/nginx/html
      - ./demo/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mcp-serper

  redis:
    image: redis:alpine
    container_name: mcp-serper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: